[template]
src = "sso-require-macros.conf.tmpl"
dest = "/etc/apache2/conf.d/sso-require-macros.conf"
prefix = "/nubis/%%PROJECT%%/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl restart apache2"
