[template]
src = "traefik.toml.tmpl"
dest = "/etc/traefik/traefik.toml"
prefix = "/nubis/%%PROJECT%%/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl restart traefik"
