#!/bin/bash

export PATH=/usr/local/bin:$PATH

CONFIG=/etc/nubis-config/nubis-sso-generated.sh

if [ ! -r "$CONFIG" ]; then
  echo "Can't read our config file : $CONFIG"
  exit 1
fi

# shellcheck disable=SC1090
. $CONFIG

if [ -z "$OPENID_SERVER_PASSPHRASE" ]; then
  NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)
  NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
  KV_PREFIX="nubis/$NUBIS_PROJECT/$NUBIS_ARENA/config"

  echo "Generating OpenID server passphrase"  
  consulate kv set "$KV_PREFIX/OpenID/Server/Passphrase" "$(uuidgen)"
fi
