forge "https://forgeapi.puppetlabs.com"

# This developer doesn't tag his releases on github
mod 'lesaux/kibana',
    :git => 'https://github.com/limed/puppet-kibana',
    :ref => '40a02395de3f4488c857e11cb5ab64579e541746'
