forge "https://forgeapi.puppetlabs.com"

# This developer doesn't tag his releases on github
mod 'lesaux/kibana',
    :git => 'https://github.com/joshuaspence/puppet-kibana4.git',
    :ref => 'kibana5'
