#!/bin/bash
# Just runs awsscout2 and symlinks report.html to index.html

/usr/local/bin/Scout2 --force --no-browser  --report-dir /var/www/html/scout --ruleset /usr/local/bin/nubis-scout-ruleset.json && {
    ln -s /var/www/html/scout/report.html /var/www/html/scout/index.html
}
